name: payworth
description: A Flutter project.
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2

  # Core
  get: ^4.6.6
  hive: ^2.2.3
  hive_flutter: ^1.1.0

  # Network
  dio: ^5.4.0

  # UI helpers
  flutter_svg: ^2.0.10
  loading_animation_widget: ^1.2.1
  dropdown_button2: ^2.3.9

  # Utilities
  syncfusion_flutter_datepicker: ^24.1.41
  passcode_screen: ^2.0.1
  virtual_keyboard_multi_language: ^1.0.3

  # FIXED PLUGINS
  fluttertoast: ^8.2.4
  flutter_native_splash: ^2.3.10

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.1
  flutter_launcher_icons: ^0.13.1
  flutter_screenutil: ^5.9.0

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/images/logo.png"
  remove_alpha_ios: true

flutter_native_splash:
  background_image: assets/images/Splash Screen (5).png
  android: true
  ios: true

flutter:
  uses-material-design: true

  assets:
    - assets/images/

  fonts:
    - family: Gilroy
      fonts:
        - asset: assets/fonts/Gilroy-Light.otf

    - family: Poppins
      fonts:
        - asset: assets/fonts/poppins/Poppins-Regular.ttf
        - asset: assets/fonts/poppins/Poppins-Bold.ttf
          weight: 700
